#!/usr/bin/env node
/**
 * Build one elifba lesson video.
 *
 *   node elifba/build.mjs --letters elif,be,te --out elifba/out/demo.mp4
 *   node elifba/build.mjs --letters all --height 1080
 *
 * Order matters and is not arbitrary: the narration is synthesised *first*,
 * because how long each spoken line turns out to be is what decides how long
 * its segment lasts. The timeline is then the single source both the picture
 * and the sound are derived from, so they cannot drift apart.
 */

import { mkdtemp, rm, stat, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import capture from '../visuals/capture/capture.mjs';
import encode from '../visuals/encode/encode.mjs';
import { buildTimeline, spokenLines } from './timeline.mjs';
import { buildTrack, normaliseTrack, synthesise } from './voice.mjs';

const execFileAsync = promisify(execFile);
const ELIFBA_DIR = path.dirname(fileURLToPath(import.meta.url));

const DEFAULTS = Object.freeze({
  letters: 'elif,be,te',
  fps: 30,
  height: 1080,
  out: path.join(ELIFBA_DIR, 'out', 'lesson.mp4'),
  keepFrames: false,
});

const USAGE = `Build an elifba lesson video (letters + ustun/esre/otre).

Usage: node elifba/build.mjs [options]

  --letters LIST   comma-separated letter ids from lesson.json, or "all"
                                                  (default ${DEFAULTS.letters})
  --height N       output height; width is 16:9   (default ${DEFAULTS.height})
  --fps N          frames per second              (default ${DEFAULTS.fps})
  --out PATH       output MP4                     (default elifba/out/lesson.mp4)
  --title TEXT     override the on-screen/spoken lesson title
  --keep-frames    keep the PNG scratch directory
  -h, --help       show this message
`;

function parseArgs(argv) {
  const opts = { ...DEFAULTS };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = () => {
      const value = argv[++i];
      if (value === undefined) throw new Error(`${arg} needs a value`);
      return value;
    };
    switch (arg) {
      case '-h': case '--help': opts.help = true; break;
      case '--letters': opts.letters = next(); break;
      case '--height': opts.height = Number(next()); break;
      case '--fps': opts.fps = Number(next()); break;
      case '--out': opts.out = next(); break;
      case '--title': opts.title = next(); break;
      case '--keep-frames': opts.keepFrames = true; break;
      default: throw new Error(`unknown option ${arg}`);
    }
  }
  if (!Number.isFinite(opts.height) || opts.height <= 0) throw new Error('--height must be positive');
  if (!Number.isFinite(opts.fps) || opts.fps <= 0) throw new Error('--fps must be positive');
  return opts;
}

/** 16:9, rounded to an even width -- yuv420p cannot encode an odd dimension. */
export function widthFor(height) {
  return Math.round((height * 16) / 9 / 2) * 2;
}

function hhmmss(seconds) {
  const s = Math.round(seconds);
  return `${Math.floor(s / 60)}m ${String(s % 60).padStart(2, '0')}s`;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    console.log(USAGE);
    return;
  }

  const lesson = JSON.parse(readFileSync(path.join(ELIFBA_DIR, 'lesson.json'), 'utf8'));
  const letterIds =
    opts.letters === 'all'
      ? lesson.letters.map((l) => l.id)
      : opts.letters.split(',').map((s) => s.trim()).filter(Boolean);
  if (letterIds.length === 0) throw new Error('--letters selected nothing');

  const height = opts.height;
  const width = widthFor(height);

  // -- 1. narration, which is what sets the pacing -------------------------
  const lines = spokenLines(lesson, letterIds, { title: opts.title });
  console.log(`[elifba] ${letterIds.length} letter(s), ${lines.length} distinct spoken line(s)`);

  const { files, durations } = await synthesise(lines, {
    cacheDir: path.join(ELIFBA_DIR, 'voice'),
    voice: lesson.voice,
    onProgress: (done, total, text, cached) =>
      console.log(`[voice] ${done}/${total} ${cached ? 'cached ' : 'synth  '} ${JSON.stringify(text)}`),
  });

  // -- 2. the timeline both halves are built from --------------------------
  const timeline = buildTimeline(lesson, letterIds, durations, { title: opts.title });
  console.log(
    `[elifba] ${timeline.segments.length} segments, ${hhmmss(timeline.totalSeconds)} ` +
      `at ${width}x${height}/${opts.fps}fps`,
  );

  await writeFile(
    path.join(ELIFBA_DIR, 'scene', 'timeline.js'),
    `/* Generated by elifba/build.mjs -- do not edit. */\nwindow.__timeline = ${JSON.stringify(timeline, null, 2)};\n`,
    'utf8',
  );

  // -- 3. frames -----------------------------------------------------------
  const framesDir = await mkdtemp(path.join(os.tmpdir(), 'elifba-frames-'));
  const outPath = path.resolve(opts.out);
  const silentPath = outPath.replace(/\.mp4$/i, '.silent.mp4');
  const trackPath = outPath.replace(/\.mp4$/i, '.track.wav');
  const audioWork = path.join(framesDir, 'audio');

  try {
    let lastPct = -1;
    const result = await capture({
      sceneUrl: path.join(ELIFBA_DIR, 'scene', 'index.html'),
      outDir: framesDir,
      width,
      height,
      fps: opts.fps,
      durationSeconds: timeline.totalSeconds,
      seed: 0,
      // The scene is DOM, not WebGL, so a software renderer costs nothing here.
      allowSoftwareRenderer: true,
      onProgress: (done, total) => {
        const pct = Math.floor((done / total) * 100);
        if (pct !== lastPct && pct % 5 === 0) {
          lastPct = pct;
          console.log(`[frames] ${pct}% (${done}/${total})`);
        }
      },
      onLog: (level, message) => {
        if (level === 'warn' || level === 'error') console.warn(`[capture] ${message}`);
      },
    });
    console.log(`[frames] ${result.frameCount} frames at ${result.msPerFrame.toFixed(0)} ms/frame`);

    // -- 4. silent video --------------------------------------------------
    await encode({
      framesDir,
      outPath: silentPath,
      fps: opts.fps,
      onProgress: () => {},
    });

    // -- 5. narration track, then mux --------------------------------------
    await buildTrack(timeline, files, { outPath: trackPath, workDir: audioWork });
    const { outPath: mixPath, measured } = await normaliseTrack(
      trackPath, path.join(audioWork, 'normalised.wav'),
    );
    if (measured) {
      console.log(`[audio] ${Number(measured.input_i).toFixed(1)} LUFS in -> -16 LUFS out`);
    }

    await execFileAsync('ffmpeg', [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-i', silentPath,
      '-i', mixPath,
      '-map', '0:v:0', '-map', '1:a:0',
      '-c:v', 'copy',
      '-c:a', 'aac', '-b:a', '192k', '-ar', '48000',
      '-shortest',
      '-movflags', '+faststart',
      outPath,
    ]);

    const info = await stat(outPath);
    console.log(`[elifba] ${outPath} (${(info.size / 1e6).toFixed(1)} MB, ${hhmmss(timeline.totalSeconds)})`);
  } finally {
    await rm(silentPath, { force: true });
    await rm(trackPath, { force: true });
    if (!opts.keepFrames) await rm(framesDir, { recursive: true, force: true });
    else console.log(`[elifba] frames kept at ${framesDir}`);
  }
}

main().catch((err) => {
  console.error(err.stack || String(err));
  process.exit(1);
});
